namespace WSMMonitor;

/// <summary>RU/EN strings for companion (WinForms) and dashboard lang token.</summary>
public static class WsmLocalization
{
    public static bool IsEnglish =>
        string.Equals(WsmConfiguration.Current.Ui.Language, "en", StringComparison.OrdinalIgnoreCase);

    /// <summary>Dashboard &lt;html lang&gt; and JS UI_LANG (en | ru).</summary>
    public static string DashboardLang => IsEnglish ? "en" : "ru";

    public static string NormalizeLang(string? s) =>
        string.Equals(s, "en", StringComparison.OrdinalIgnoreCase) ? "en" : "ru";

    /// <summary><c>false</c> when <paramref name="workMode"/> is <c>service</c> (prefer service agent).</summary>
    public static bool IsCompanionWorkMode(string? workMode) =>
        !string.Equals(workMode, "service", StringComparison.OrdinalIgnoreCase);

    public static string T(string key) => IsEnglish ? En(key) : Ru(key);

    public static string Tf(string key, params object?[] args)
    {
        var s = T(key);
        try
        {
            return string.Format(System.Globalization.CultureInfo.InvariantCulture, s, args);
        }
        catch
        {
            return s;
        }
    }

    private static string Ru(string key) => key switch
    {
        "AppTitle" => "WSM Monitor Companion",
        "SplashStarting" => "Запуск…",
        "CompanionLine" => "WSM Monitor Companion",
        "BtnSettings" => "Настройки…",
        "BtnDashboard" => "Открыть веб-дашборд",
        "BtnCopyDiag" => "Скопировать диагностику",
        "BtnSvcStart" => "Старт службы",
        "BtnSvcStop" => "Стоп службы",
        "BtnSvcRestart" => "Рестарт службы",
        "TrayShow" => "Показать статус",
        "TrayStatus" => "Статус WSM",
        "TraySettings" => "Настройки…",
        "TrayDashboard" => "Открыть веб-дашборд",
        "TraySvcStart" => "Старт службы",
        "TraySvcStop" => "Стоп службы",
        "TraySvcRestart" => "Рестарт службы",
        "TrayExit" => "Выход",
        "AgentPrefix" => "Агент:",
        "ServicePrefix" => "Служба:",
        "HttpPrefix" => "HTTP:",
        "HttpPortFmt" => "порт {0}",
        "LastHb" => "Последний heartbeat:",
        "DetailsPrefix" => "Детали:",
        "AgentRunning" => "Agent running",
        "AgentStopped" => "Agent stopped",
        "AgentUnknown" => "Agent unknown",
        "HttpListening" => "HTTP listening",
        "HttpNotListening" => "HTTP not listening",
        "HttpUnreachable" => "HTTP not reachable",
        "HttpUnavailable" => "HTTP unavailable",
        "AgentUnavailable" => "Agent unavailable",
        "NoPayload" => "No status payload",
        "DetailNoErrors" => "Нет ошибок",
        "ModeEmbeddedPrimary" => "Агент в этом exe на порту {0}.",
        "ModeEmbeddedAlt" => "Агент в этом exe на порту {0} (служба на {1} может отдавать старую вёрстку).",
        "ModeServiceOnly" => "Только служба на {0} — встроенный агент не поднят; см. детали выше.",
        "DiagVersion" => "Версия",
        "DiagBuild" => "Сборка (UTC)",
        "DiagPid" => "PID процесса",
        "DiagDashPort" => "Порт дашборда (браузер)",
        "DiagApiPort" => "Порт API агента",
        "DiagHistory" => "История",
        "DiagReady" => "Ready",
        "DiagSvcMode" => "Служба",
        "DiagAgent" => "Агент",
        "DiagHttp" => "HTTP",
        "DiagLastSample" => "Последний сбор",
        "DiagError" => "Ошибка",
        "DiagExe" => "Exe",
        "DiagHeader" => "WSM Monitor — диагностика",
        "DiagNoData" => "WSM: нет данных heartbeat (агент недоступен).",
        "DiagCopied" => "Диагностика скопирована в буфер обмена.",
        "AdminRequired" => "Нужны права администратора для управления службой.",
        "SvcAlreadyRunning" => "Служба уже запущена.",
        "SvcAlreadyStarting" => "Служба уже запускается.",
        "SvcAlreadyStopped" => "Служба уже остановлена.",
        "SvcAlreadyStopping" => "Служба уже останавливается.",
        "MsgVersionTitle" => "WSM Monitor — несовпадение версии",
        "BalloonTitle" => "WSM Monitor",
        "BalloonAgentUrl" => "Локальный агент: http://127.0.0.1:{0}/",
        "SettingsSaved" => "Сохранено в appsettings.local.json. Порт, SQLite, журнал (путь, срок хранения файлов, почасовой блок метрик), режим работы, язык и датчики — перезапустите companion и службу (если есть), чтобы агент подхватил интервалы; путь к журналу и срок хранения применяются сразу.",
        "SettingsSaveErr" => "Не удалось сохранить: ",
        "SettingsTitle" => "Настройки WSM Monitor",
        "TabAgent" => "Агент",
        "TabLogging" => "Журнал",
        "TabHistory" => "История",
        "TabSigma" => "Sigma",
        "TabSensors" => "Датчики",
        "TabUi" => "Интерфейс",
        "LblWorkMode" => "Режим работы",
        "WorkModeService" => "Служба",
        "WorkModeCompanion" => "Компаньон",
        "LblLang" => "Язык",
        "LangRu" => "Русский",
        "LangEn" => "English",
        "BtnOk" => "OK",
        "BtnApply" => "Применить",
        "BtnTestConfig" => "Проверить",
        "BtnCancel" => "Отмена",
        "MsgInstallAdmin" => "Для установки/удаления службы запустите от имени администратора.",
        "MsgBoxTitle" => "WSM Monitor",
        "ConfigTestTitle" => "Проверка конфигурации",
        "ConfigTestHeader" => "Результаты проверки:",
        "ConfigTestApi" => "Доступность API агента",
        "ConfigTestLogWrite" => "Права на запись логов",
        "ConfigTestService" => "Статус службы",
        "ConfigTestSensors" => "Доступ к датчикам (LHM)",
        "ConfigTestSvcMissing" => "Служба не установлена",
        "ConfigTestSkipped" => "Пропущено (LHM отключен)",
        "ConfigTestOk" => "OK",
        "ConfigTestFail" => "Ошибка",
        "AppAlreadyRunning" => "WSM Monitor уже запущен (иконка в трее).",
        "StatusAgentFmt" => "Агент: {0}",
        "StatusServiceFmt" => "Служба: {0}",
        "StatusHttpFmt" => "HTTP: {0} · порт {1}",
        "StatusLastHbFmt" => "Последний heartbeat: {0}",
        "DetailsLineFmt" => "Детали: {0}",
        "TrayTextFmt" => "WSM {0} | {1} | {2}",
        "DetailCompanionAltPortFmt" => "Режим «Компаньон»: встроенный агент на {1} (порт {0} занят). Дашборд: http://127.0.0.1:{1}/",
        "DetailPrimaryBadApiFmt" => "На {0} нет корректного WSM API (или порт занят). Дашборд этой сборки: http://127.0.0.1:{1}/ — кнопка «Открыть веб-дашборд» ведёт сюда.",
        "DetailEmbNotStartedFmt" => "Встроенный агент не запущен (порты {0}–{1} недоступны). Остановите службу WSMMonitor или процесс на {0}.",
        "DetailDashThisBuildFmt" => "Дашборд этой сборки: http://127.0.0.1:{0}/ — {1}. Кнопка «Открыть веб-дашборд» ведёт сюда.",
        "DetailWhoService" => "на {0} работает служба (часто старый exe)",
        "DetailWhoOtherFmt" => "на {0} отвечает другой агент (версия «{1}», ожидалась «{2}»)",
        "DetailWrongVerNoReserveFmt" => "На {0} агент другой версии («{1}»); резерв {2}–{3} недоступен. Остановите процесс/службу на {0} или освободите порт.",
        "EmbAgentFailFmt" => "Встроенный агент (порт {0}): {1}",
        "DetailReconcileDashFmt" => "Дашборд этой сборки: http://127.0.0.1:{0}/ — агент на {1} не «{2}» (получено: «{3}»). Кнопка «Открыть веб-дашборд» ведёт сюда.",
        "DiagHbFmt" => "Версия {0} · сборка {1} · PID {2} · API {3} · история {4} · ready={5}",
        "VerMismatchOpen1Fmt" => "Агент на http://127.0.0.1:{0}/ не совпадает с этим companion («{1}»). Получено: «{2}».",
        "VerMismatchOpen2" => "Не удалось поднять встроенный агент на резервном порту — проверьте, что порты не заняты другими процессами.",
        "VerMismatchOpen3" => "Решение: sc stop WSMMonitor, замените exe в каталоге из binPath на свежий из publish, sc start WSMMonitor.",
        "VerMismatchOpenBinFmt" => "Текущий BINARY_PATH_NAME: {0}",
        "SettingsChkLog" => "Включить запись в файл",
        "SettingsLblLogPath" => "Путь к файлу (относительно exe)",
        "SettingsLblLogLevel" => "Минимальный уровень",
        "SettingsLblLogRetentionDays" => "Хранение файлов журнала, дней",
        "SettingsChkHourlySummary" => "Почасовой блок в журнале (метрики и ошибки Windows)",
        "SettingsLblHourlySummaryHours" => "Интервал почасового блока (ч)",
        "SettingsChkSqlite" => "SQLite для истории метрик",
        "SettingsLblSqliteFile" => "Файл SQLite",
        "SettingsLblRetention" => "Хранение, дней",
        "SettingsBrowse" => "Обзор…",
        "SettingsLblSigmaFile" => "Файл suppressions",
        "SettingsAgentPort" => "Порт HTTP агента",
        "SettingsAgentHist" => "Интервал записи истории (с)",
        "SettingsLhmMain" => "LibreHardwareMonitor (датчики температуры)",
        "SettingsLhmCpu" => "CPU",
        "SettingsLhmGpu" => "GPU",
        "SettingsLhmMobo" => "Материнская плата",
        "SettingsLhmMem" => "Модули памяти",
        "SettingsLhmStorage" => "Накопители",
        "SettingsLhmFan" => "Контроллеры вентиляторов",
        "SettingsLhmPsu" => "БП",
        "SettingsLhmMaxRow" => "Макс. строк температуры в API",
        "SettingsDlgSqliteTitle" => "Файл базы истории",
        "SettingsDlgSqliteFilter" => "SQLite (*.db)|*.db|Все файлы|*.*",
        "SettingsDlgSigmaTitle" => "JSON подавлений Sigma",
        "SettingsDlgSigmaFilter" => "JSON (*.json)|*.json|Все файлы|*.*",
        _ => key
    };

    private static string En(string key) => key switch
    {
        "AppTitle" => "WSM Monitor Companion",
        "SplashStarting" => "Starting…",
        "CompanionLine" => "WSM Monitor Companion",
        "BtnSettings" => "Settings…",
        "BtnDashboard" => "Open web dashboard",
        "BtnCopyDiag" => "Copy diagnostics",
        "BtnSvcStart" => "Start service",
        "BtnSvcStop" => "Stop service",
        "BtnSvcRestart" => "Restart service",
        "TrayShow" => "Show status",
        "TrayStatus" => "WSM status",
        "TraySettings" => "Settings…",
        "TrayDashboard" => "Open web dashboard",
        "TraySvcStart" => "Start service",
        "TraySvcStop" => "Stop service",
        "TraySvcRestart" => "Restart service",
        "TrayExit" => "Exit",
        "AgentPrefix" => "Agent:",
        "ServicePrefix" => "Service:",
        "HttpPrefix" => "HTTP:",
        "HttpPortFmt" => "port {0}",
        "LastHb" => "Last heartbeat:",
        "DetailsPrefix" => "Details:",
        "AgentRunning" => "Agent running",
        "AgentStopped" => "Agent stopped",
        "AgentUnknown" => "Agent unknown",
        "HttpListening" => "HTTP listening",
        "HttpNotListening" => "HTTP not listening",
        "HttpUnreachable" => "HTTP not reachable",
        "HttpUnavailable" => "HTTP unavailable",
        "AgentUnavailable" => "Agent unavailable",
        "NoPayload" => "No status payload",
        "DetailNoErrors" => "No errors",
        "ModeEmbeddedPrimary" => "Embedded agent in this exe on port {0}.",
        "ModeEmbeddedAlt" => "Embedded agent on port {0} (service on {1} may serve an older dashboard).",
        "ModeServiceOnly" => "Service only on {0} — embedded agent not started; see details above.",
        "DiagVersion" => "Version",
        "DiagBuild" => "Build (UTC)",
        "DiagPid" => "Process ID",
        "DiagDashPort" => "Dashboard port (browser)",
        "DiagApiPort" => "Agent API port",
        "DiagHistory" => "History",
        "DiagReady" => "Ready",
        "DiagSvcMode" => "Service",
        "DiagAgent" => "Agent",
        "DiagHttp" => "HTTP",
        "DiagLastSample" => "Last sample",
        "DiagError" => "Error",
        "DiagExe" => "Exe",
        "DiagHeader" => "WSM Monitor — diagnostics",
        "DiagNoData" => "WSM: no heartbeat data (agent unreachable).",
        "DiagCopied" => "Diagnostics copied to clipboard.",
        "AdminRequired" => "Administrator rights are required to control the service.",
        "SvcAlreadyRunning" => "Service is already running.",
        "SvcAlreadyStarting" => "Service is already starting.",
        "SvcAlreadyStopped" => "Service is already stopped.",
        "SvcAlreadyStopping" => "Service is already stopping.",
        "MsgVersionTitle" => "WSM Monitor — version mismatch",
        "BalloonTitle" => "WSM Monitor",
        "BalloonAgentUrl" => "Local agent: http://127.0.0.1:{0}/",
        "SettingsSaved" => "Saved to appsettings.local.json. Port, SQLite, logging (path, file retention, hourly metrics block), work mode, language, and sensors — restart companion and the service (if any) so the agent picks up intervals; log path and retention apply immediately.",
        "SettingsSaveErr" => "Could not save: ",
        "SettingsTitle" => "WSM Monitor — settings",
        "TabAgent" => "Agent",
        "TabLogging" => "Logging",
        "TabHistory" => "History",
        "TabSigma" => "Sigma",
        "TabSensors" => "Sensors",
        "TabUi" => "Interface",
        "LblWorkMode" => "Work mode",
        "WorkModeService" => "Service",
        "WorkModeCompanion" => "Companion",
        "LblLang" => "Language",
        "LangRu" => "Russian",
        "LangEn" => "English",
        "BtnOk" => "OK",
        "BtnApply" => "Apply",
        "BtnTestConfig" => "Check",
        "BtnCancel" => "Cancel",
        "MsgInstallAdmin" => "Run as administrator to install or remove the service.",
        "MsgBoxTitle" => "WSM Monitor",
        "ConfigTestTitle" => "Configuration check",
        "ConfigTestHeader" => "Check results:",
        "ConfigTestApi" => "Agent API availability",
        "ConfigTestLogWrite" => "Log write permissions",
        "ConfigTestService" => "Service status",
        "ConfigTestSensors" => "Sensor access (LHM)",
        "ConfigTestSvcMissing" => "Service not installed",
        "ConfigTestSkipped" => "Skipped (LHM is disabled)",
        "ConfigTestOk" => "OK",
        "ConfigTestFail" => "Failed",
        "AppAlreadyRunning" => "WSM Monitor is already running (tray icon).",
        "StatusAgentFmt" => "Agent: {0}",
        "StatusServiceFmt" => "Service: {0}",
        "StatusHttpFmt" => "HTTP: {0} · port {1}",
        "StatusLastHbFmt" => "Last heartbeat: {0}",
        "DetailsLineFmt" => "Details: {0}",
        "TrayTextFmt" => "WSM {0} | {1} | {2}",
        "DetailCompanionAltPortFmt" => "Companion mode: embedded agent on {1} (port {0} busy). Dashboard: http://127.0.0.1:{1}/",
        "DetailPrimaryBadApiFmt" => "Port {0} has no valid WSM API (or port is busy). This build’s dashboard: http://127.0.0.1:{1}/ — the Open web dashboard button uses this URL.",
        "DetailEmbNotStartedFmt" => "Embedded agent not started (ports {0}–{1} unavailable). Stop the WSMMonitor service or the process on {0}.",
        "DetailDashThisBuildFmt" => "This build’s dashboard: http://127.0.0.1:{0}/ — {1}. The Open web dashboard button uses this URL.",
        "DetailWhoService" => "service on {0} is running (often an old exe)",
        "DetailWhoOtherFmt" => "another agent on {0} (version \"{1}\", expected \"{2}\")",
        "DetailWrongVerNoReserveFmt" => "Agent on {0} is a different version (\"{1}\"); reserve ports {2}–{3} are unavailable. Stop the process/service on {0} or free a port.",
        "EmbAgentFailFmt" => "Embedded agent (port {0}): {1}",
        "DetailReconcileDashFmt" => "This build’s dashboard: http://127.0.0.1:{0}/ — agent on {1} is not \"{2}\" (got: \"{3}\"). The Open web dashboard button uses this URL.",
        "DiagHbFmt" => "Version {0} · build {1} · PID {2} · API {3} · history {4} · ready={5}",
        "VerMismatchOpen1Fmt" => "Agent at http://127.0.0.1:{0}/ does not match this companion (\"{1}\"). Received: \"{2}\".",
        "VerMismatchOpen2" => "Could not start the embedded agent on a reserve port — check that ports are not used by other processes.",
        "VerMismatchOpen3" => "Fix: sc stop WSMMonitor, replace the exe in binPath with the latest from publish, sc start WSMMonitor.",
        "VerMismatchOpenBinFmt" => "Current BINARY_PATH_NAME: {0}",
        "SettingsChkLog" => "Write logs to file",
        "SettingsLblLogPath" => "Log file path (relative to exe)",
        "SettingsLblLogLevel" => "Minimum level",
        "SettingsLblLogRetentionDays" => "Log file retention, days",
        "SettingsChkHourlySummary" => "Hourly log block (metrics and Windows errors)",
        "SettingsLblHourlySummaryHours" => "Hourly block interval (h)",
        "SettingsChkSqlite" => "SQLite for metrics history",
        "SettingsLblSqliteFile" => "SQLite file",
        "SettingsLblRetention" => "Retention, days",
        "SettingsBrowse" => "Browse…",
        "SettingsLblSigmaFile" => "Suppressions file",
        "SettingsAgentPort" => "Agent HTTP port",
        "SettingsAgentHist" => "History write interval (s)",
        "SettingsLhmMain" => "LibreHardwareMonitor (temperature sensors)",
        "SettingsLhmCpu" => "CPU",
        "SettingsLhmGpu" => "GPU",
        "SettingsLhmMobo" => "Motherboard",
        "SettingsLhmMem" => "Memory modules",
        "SettingsLhmStorage" => "Storage",
        "SettingsLhmFan" => "Fan controllers",
        "SettingsLhmPsu" => "PSU",
        "SettingsLhmMaxRow" => "Max temperature rows in API",
        "SettingsDlgSqliteTitle" => "History database file",
        "SettingsDlgSqliteFilter" => "SQLite (*.db)|*.db|All files|*.*",
        "SettingsDlgSigmaTitle" => "Sigma suppressions JSON",
        "SettingsDlgSigmaFilter" => "JSON (*.json)|*.json|All files|*.*",
        _ => key
    };
}
